---
version: '2'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:3.1.1
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka0:
    container_name: kafka0 
    image: confluentinc/cp-enterprise-kafka:3.1.1
    hostname: kafka0 
    depends_on:
      - zookeeper
    ports:
      - '9090:9090'
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_BROKER_RACK: 1
      KAFKA_LOG_DIRS: '/var/lib/kafka/kafka0'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka0:9090'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka0:9090
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 2
      CONFLUENT_METRICS_REPORTER_PUBLISH_MS: 1000


  kafka1:
    container_name: kafka1
    image: confluentinc/cp-enterprise-kafka:3.1.1
    hostname: kafka1
    depends_on:
      - zookeeper
    ports:
      - '9091:9091'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: 1
      KAFKA_LOG_DIRS: '/var/lib/kafka/kafka1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka1:9091'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka0:9090
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 2
      CONFLUENT_METRICS_REPORTER_PUBLISH_MS: 1000


  kafka2:
    container_name: kafka2
    image: confluentinc/cp-enterprise-kafka:3.1.1
    hostname: kafka2
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_BROKER_RACK: 1
      KAFKA_LOG_DIRS: '/var/lib/kafka/kafka2'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka2:9092'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka0:9090
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 2
      CONFLUENT_METRICS_REPORTER_PUBLISH_MS: 1000

  kafka3:
    container_name: kafka3
    image: confluentinc/cp-enterprise-kafka:3.1.1
    hostname: kafka3
    depends_on:
      - zookeeper
    ports:
      - '9093:9093'
    environment:
      KAFKA_BROKER_ID: 3 
      KAFKA_BROKER_RACK: 2 
      KAFKA_LOG_DIRS: '/var/lib/kafka/kafka3'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka3:9093'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka0:9090
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 2
      CONFLUENT_METRICS_REPORTER_PUBLISH_MS: 1000

  kafka4:
    container_name: kafka4
    image: confluentinc/cp-enterprise-kafka:3.1.1
    hostname: kafka4
    depends_on:
      - zookeeper
    ports:
      - '9094:9094'
    environment:
      KAFKA_BROKER_ID: 4 
      KAFKA_BROKER_RACK: 2 
      KAFKA_LOG_DIRS: '/var/lib/kafka/kafka4'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka4:9094'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka0:9090
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 2
      CONFLUENT_METRICS_REPORTER_PUBLISH_MS: 1000

  kafka5:
    container_name: kafka5
    image: confluentinc/cp-enterprise-kafka:3.1.1
    hostname: kafka5
    depends_on:
      - zookeeper
    ports:
      - '9095:9095'
    environment:
      KAFKA_BROKER_ID: 5
      KAFKA_BROKER_RACK: 2 
      KAFKA_LOG_DIRS: '/var/lib/kafka/kafka5'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka5:9094'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka0:9090
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 2
      CONFLUENT_METRICS_REPORTER_PUBLISH_MS: 1000
