---
version: '2'

volumes:
  zookeeper:
  kafka:

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:3.1.1
    hostname: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zookeeper:/var/lib/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka0:
    container_name: kafka0 
    image: confluentinc/cp-enterprise-kafka:3.1.1
    hostname: kafka0 
    depends_on:
      - zookeeper
    ports:
      - ':9090:9090'
    volumes:
      - kafka:/var/lib/kafka
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_BROKER_RACK: 1
      KAFKA_LOG_DIRS: '/var/lib/kafka/kafka0'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://0.0.0.0:9090'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka0:9090
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 2
      CONFLUENT_METRICS_REPORTER_PUBLISH_MS: 1000

  kafka1:
    container_name: kafka1
    image: confluentinc/cp-enterprise-kafka:3.1.1
    hostname: kafka1
    depends_on:
      - zookeeper
    ports:
      - ':9091:9091'
    volumes:
      - kafka:/var/lib/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: 1
      KAFKA_LOG_DIRS: '/var/lib/kafka/kafka1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://0.0.0.0:9091'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka0:9090
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 2
      CONFLUENT_METRICS_REPORTER_PUBLISH_MS: 1000

  kafka2:
    container_name: kafka2
    image: confluentinc/cp-enterprise-kafka:3.1.1
    hostname: kafka2
    depends_on:
      - zookeeper
    ports:
      - ':9092:9092'
    volumes:
      - kafka:/var/lib/kafka
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_BROKER_RACK: 1
      KAFKA_LOG_DIRS: '/var/lib/kafka/kafka2'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://0.0.0.0:9092'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka0:9090
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 2
      CONFLUENT_METRICS_REPORTER_PUBLISH_MS: 1000

  schema_registry:
    container_name: schema_registry
    image: confluentinc/cp-schema-registry:3.1.1
    hostname: schema_registry
    depends_on:
      - zookeeper
      - kafka0
      - kafka1
      - kafka2
    ports:
      - ':8081:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'

  kafka_rest:
    container_name: kafka_rest
    image: confluentinc/cp-kafka-rest:3.1.1
    hostname: kafka_rest
    depends_on:
      - zookeeper
      - kafka0
      - kafka1
      - kafka2
      - schema_registry
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_HOST_NAME: "kafka_rest"
      KAFKA_REST_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: "http://schema_registry:8081"

  connect:
    container_name: connect
    image: confluentinc/cp-kafka-connect:3.1.1
    hostname: connect
    depends_on:
      - zookeeper
      - kafka0
      - kafka1
      - kafka2
      - schema_registry
    ports:
      - "8083:8083"
    environment:
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
      CONNECT_BOOTSTRAP_SERVERS: 'kafka0:9090,kafka1:9091,kafka2:9092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter" 
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    volumes:
      - /tmp/quickstart/file:/tmp/quickstart 

  control-center:
    container_name: control-center
    image: confluentinc/cp-enterprise-control-center:3.1.1
    hostname: control-center
    depends_on:
      - zookeeper
      - kafka0
      - kafka1
      - kafka2
      - schema_registry
      - connect
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka0:9090,kafka1:9091,kafka2:9092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_CONNECT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      PORT: 9021

